name: "MustacheEE"
platform: "pytorch_libtorch"
input [{
  name: "x__0"
  data_type: TYPE_FP32
  dims: [-1, 4]
}, {
  name: "batch__1"
  data_type: TYPE_INT64
  dims: [-1]
}, {
  name: "graphx__2"
  data_type: TYPE_FP32
  dims: [-1]
}]
output [{
  name: "dscb__0"
  data_type: TYPE_FP32
  dims: [-1, 6]
}]
model_repository_agents {
  agents [{
    name: "checksum"
    parameters {
      key: "MD5:1/model.pt"
      value: "17e8258349456152010be91b08879db8"
    }
  }]
}
